# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.cache/wt [current_project]
set_property parent.project_path D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/LED.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/clk_div.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/DataLate.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/PC.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/RegFile.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/InsMemory.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/Extend.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/DataSelect.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/DataMemory.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/controlUnit.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/ALU.v
  D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/sources_1/new/main.v
}
read_xdc D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/constrs_1/new/1.xdc
set_property used_in_implementation false [get_files D:/vivado/MultiPeriodCPU_basys/MultiPeriodCPU.srcs/constrs_1/new/1.xdc]

synth_design -top main -part xc7a35tcpg236-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
